### ISSUE TITLE
Error Module not found: Error: Can't resolve 'react-native'

### ISSUE THREAD

**Issue by harishdrish123** [juhoen/hybrid-crypto-js#10]
Hello all,

I am using hybride-crypto-js with webpack but getting below error:

ERROR in ../node_modules/hybrid-crypto-js/lib/keymanager.js
Module not found: Error: Can't resolve 'react-native' in '/home/hyper1/Sawtooth-projects/webpkdemoo/node_modules/hybrid-crypto-js/lib'
@ ../node_modules/hybrid-crypto-js/lib/keymanager.js 1:0-42 30:8-20 40:8-20
@ ../node_modules/hybrid-crypto-js/lib/index.js

Can anyone help me to solve this issue?

**Comment by muzkle** [comment]
I've got this same problem while using an Angular 4 project.
Any fix idea or that?

**Comment by actuallydan** [comment]
I'm getting a similar issue with a react web project; running the example code works in a fresh [codesandbox project](https://codesandbox.io/s/musing-raman-h9v2x), but using the exact same code doesn't work in a create-react-app project.

I'm guessing no one has found a solution yet?

**Comment by Polelo-Monareng** [comment]
Hello all,
The hybrid-crypt package was written for React Native, so you have to comment the react native part out.

In hybrid-crypto-js>lib>index.js you have to comment the following section.

// Include keyManager if running React Native
// if (typeof navigator != 'undefined' && navigator.product == 'ReactNative') {
// var keyManager = require('./keymanager');
// libs['keyManager'] = keyManager;
// }

It should compile if you make that change. 

Problem is that each time you add a new package you have to comment that code again. Don't know if one can comment that code when you import hybride-crypto-js

**Comment by juhoen** [comment]
This should be now fixed. Key management is now deprecated and all the relations to react-native are gone.
