### ISSUE TITLE
Encrypt and decrypt an object

### ISSUE THREAD

**Issue by Mahmoud85** [juhoen/hybrid-crypto-js#11]
when I encrypt an object instead of only a string as in the example , I get no error but when tried to decrypt it , I only get the output as [object object], I can't get the real data , am I doing something wrong or hybrid-crypto-js can only encrypt and decrypt simple strings

**Comment by joshuaquek** [comment]
If not, just stringify the object before encrypting then parse it back again after decrypting?

**Comment by juhoen** [comment]
Hybrid-crypto-js only supports basic strings. Object could be converted into string using JSON.stringify() before encrypring and parsed after decryption using JSON.parse().
