### ISSUE TITLE
Crypt or crypt is not defined hybrid-crypto.min.js

### ISSUE THREAD

**Issue by DreamUFO** [juhoen/hybrid-crypto-js#15]
I use hybrid-crypto.min.js in local file,open in brower for testing.
when use new Crypt() or new crypt() ,both exception is 'Uncaught TypeError: (C)crypt is not a constructor'.
must use in webpack?
can anyone help?

**Comment by radleylewis** [comment]
Hi, I am also experiencing this issue. Any progress?

**Comment by liebig** [comment]
Same problem here. Any news?

**Comment by pwFoo** [comment]
@juhoen 
Seems the minified file isn't refreshed? CHanges in lib are newer then the generated hybrid-crypto.min.js file?
Is there an updated / working version available?

**Comment by iLyxa3D** [comment]
Did you find out how to use the web version of the library  **hybrid-crypto.min.js**? 
Can you show a simple example for React (web) implementation for it?

**Comment by juhoen** [comment]
I updated library recently and based on my testing with React project, everything works just fine. Also importing:

```
const { Crypt, RSA } = require('hybrid-crypto-js');
```
