### ISSUE TITLE
Not working on native device

### ISSUE THREAD

**Issue by adkandari** [juhoen/hybrid-crypto-js#16]
Hi, the decryption works perfectly on a simulator but when testing in real iPhone 6s, its not working.

**Comment by geoff-ellison** [comment]
We have this issue also.

**Comment by geoff-ellison** [comment]
FYI this was using React Native 57.1, and testing on several iPhones (including 6 and 7).

> We have this issue also. In terms of generating keys.
> Interestingly, it seems to work fine (on a device) for generating 1024 bit keys, but does not work for higher strengths. We've tested 2048 and 4096 with various rsaStandard values (none, 'RSA-OAEP' and 'RSAES-PKCS1-V1_5').

**Comment by juhoen** [comment]
Hello,
Based on my testing with native Android device key generation works, but takes some time. Over 1 minute when generating 4096 bit key. Is that the case on iPhone also?

**Comment by geoff-ellison** [comment]
> Based on my testing with native Android device key generation works, but takes some time. Over 1 minute when generating 4096 bit key. Is that the case on iPhone also?

Both 2048 and 4096 do not complete key generation after 1 minute. Only 1024 works, which completes very quickly.
Generating 4096-bit keys in a web browser takes about 5-10 seconds on average, with the longest being about 25 seconds.

**Comment by geoff-ellison** [comment]
Hey @juhoen do you have any update on this?
We are very keen to get it working.

Alternatively, if there is no fix, can you suggest another way that we can generate the keypairs, to produce keys that will still be compatible with hybrid-crypto-js?

Thanks

**Comment by 3bodyZZ** [comment]
> Alternatively, if there is no fix, can you suggest another way that we can generate the keypairs, to produce keys that will still be compatible with hybrid-crypto-js?
> 


I had the same issue , and fixed it using react native "multi threading "

**Comment by geoff-ellison** [comment]
> I had the same issue , and fixed it using react native "multi threading "

Thanks @3bodyZZ we'd like to give that a try. Any chance you could paste a relevant code snippet? (for activating multi-threading, and/or generating the keys)

Many thanks

**Comment by 3bodyZZ** [comment]
> Any chance you could paste a relevant code snippet? (for activating multi-threading, and/or generating the keys)
> 
> Many thanks

@geoff-ellison it is pretty simple just follow the examples from https://github.com/joltup/react-native-threads to suit your needs

**Comment by geoff-ellison** [comment]
> @geoff-ellison it is pretty simple just follow the examples from https://github.com/joltup/react-native-threads to suit your needs

Thanks @3bodyZZ - will give that a go!

**Comment by juhoen** [comment]
This seems to be solved.
