### ISSUE TITLE
Error: Invalid PEM formatted message, while using "var encrypted = crypt.encrypt(publicKey, message);"

### ISSUE THREAD

**Issue by mayursarode4** [juhoen/hybrid-crypto-js#21]
All steps done for using this library, but getting below error,
`Error: Invalid PEM formatted message.
    at Object.pem.decode (pem.js:185)
    at Object.pki.publicKeyFromPem (x509.js:752)
    at crypt.js:69
    at Array.map (<anonymous>)
    at Crypt.encrypt (crypt.js:67)
    at App.js:117
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:289
    at _callTimer (JSTimers.js:146)`

while using 
**var encrypted = crypt.encrypt(publicKey, message);**
Please suggest some solution to it, as I need to encrypt plain text using public key received from an API.

**Comment by YvesAmmann** [comment]
Check, if your public key is like the following example:

-----BEGIN RSA PUBLIC KEY-----
MIIJKAIBAAKCAgEAzyog3yx1Kx3xsFkXYWE8D1iFplFfpIXGs+UKGf8KXqU/Of4o...
-----END RSA PUBLIC KEY-----

I had the same error, if I try only with die Base64-encoded message without the BEGIN and END lines.
