### ISSUE TITLE
How to decypt data with php

### ISSUE THREAD

**Issue by santhoshvr** [juhoen/hybrid-crypto-js#26]
Please tell me how to decrypt the data using the php.
Actually i encrypted the data using hybrid-crypto-js.
So i want to decrypt using backend php.

**Comment by juhoen** [comment]
Decryption logic can be found from the source code:

https://github.com/juhoen/hybrid-crypto-js/blob/75d0526e029cd61db9dd8d1827a300967e30fd56/src/crypt.js#L220-L276
