### ISSUE TITLE
rsaStandard isnt actually used

### ISSUE THREAD

**Issue by sirpy** [juhoen/hybrid-crypto-js#28]
it is never passed to node-forge

**Comment by geoff-ellison** [comment]
This explains some of the problems we've been having generating keys.
We worked around it by using a different lib for keygen (react-native-rsa-native) but it would be great if this could be fixed so we could use the lib as it is intended.
Any thoughts on this @juhoen ? Thanks.

**Comment by juhoen** [comment]
Good notice, I'll take a look on this in next week!

**Comment by juhoen** [comment]
Version [0.2.3](https://github.com/juhoen/hybrid-crypto-js/releases/tag/v0.2.3) is now out. Added possibility to tweak both RSA and AES standards.
