### ISSUE TITLE
How many public keys in Encryption

### ISSUE THREAD

**Issue by chittasec** [juhoen/hybrid-crypto-js#29]
Hi,

var encrypted = crypt.encrypt([publicKey1, publicKey2, publicKey3], message);

  Regarding encrypting with multiple public keys , is there any limit on how many public keys it can encrypt with ?
If there is a limit , can it be increased ?

Thanks,
Chitta

**Comment by juhoen** [comment]
Hey! There is no such limit. However, the size of the encrypted message increases per each encryption key as keys' fingerprints and encrypted AES keys must be stored into encrypted message:

```js
{
    "v": "hybrid-crypto-js_0.1.2",        // Current package version
    "iv": "CmtyaZTyzoAp1mTNUTztic0v1...", // Initialization vector
    "keys": {                             // Encrypted AES keys by RSA fingerprints
        "85:3d:10:e1:56...": "bHaTF9...",
        "d3:48:6a:e9:13...": "t9eds3..."
    },
    "cipher": "+iwVFsC2dECBQvwcm9DND..."  // Actual encrypted message
    "signature": "sdL93kfdm12feds3C2..."  // Signature (optional)
}
```
