### ISSUE TITLE
Build issue for Android

### ISSUE THREAD

**Issue by Drienn** [juhoen/hybrid-crypto-js#3]
I havent yet found a way to resolve this issue: 
![image](https://user-images.githubusercontent.com/27447016/36348622-08645488-1431-11e8-87b5-9d04a76ef3e7.png)

I've tried to follow the steps provided by android studios but they did not seem to resolve the issue

**Comment by juhoen** [comment]
Hi, thanks for reporting. I'll take a look.

**Comment by Drienn** [comment]
Hey thanks! I actually figured it out, it was with another package I was trying out prior to finding yours! Sorry about that! The Android is I reported also was the same package that I was using prior, ill close that one too. Thanks for your response though! :-)
