### ISSUE TITLE
Cannot generate AES key

### ISSUE THREAD

**Issue by Sadat2803** [juhoen/hybrid-crypto-js#30]

**Comment by juhoen** [comment]
You are not supposed to generate AES key using this library. `Crypt.encrypt` method does it for you, under the hood. AES keys are generated and they are encrypted using the RSA public key, and attached into encrypted message's payload.

**Comment by Sadat2803** [comment]
Thank you very much for your response.

Le lun. 10 août 2020 à 06:14, Juho Enala <notifications@github.com> a
écrit :
