### ISSUE TITLE
Initialization vector length for encryption not customizable

### ISSUE THREAD

**Issue by simomat** [juhoen/hybrid-crypto-js#32]
The initialization vector (IV) is a common parameter for several encryption algorythms and is chosen randomly to enhance encryption relyability. At least for AES, the length of IV is variable and thus should be customizable.

In current implementation, an IV length of 32 byte is hardcoded:

```JavaScript
const iv = forge.random.getBytesSync(32);
```

This makes it incopatible with certain decryption standards which assume a different length of IV.

Possible solution: make IV length a parameter.

**Comment by juhoen** [comment]
Thank you for your input! Your pull request is now merged and version v0.2.4 is published to npm 🙂

**Comment by simomat** [comment]
Cool, thanks!
