### ISSUE TITLE
Unable to save decrypted image.

### ISSUE THREAD

**Issue by fuelxc** [juhoen/hybrid-crypto-js#4]
I think this might not be entirely an issue with this library as the same code essentially work in react native, but on the web, the file generated by the JS is constantly "corrupted".

`
imageData = crypt.decrypt(privateKey(), encrypted).message;
`

The data coming out from that doesn't seem to be the same in react native and the web for binary data.

I save it off to a file and compare the size is different, original 1.9m vs encrypted and decrypted 1.8m

**Comment by fuelxc** [comment]
further looking through the code it might be as simple as being able to request the bytes instead of the utf-8 in `decrypt(privateKey, encrypted)` in https://github.com/juhoen/hybrid-crypto-js/blob/master/lib/crypt.js#L106

**Comment by juhoen** [comment]
Hi and thanks for the issue and a possible solution. Unfortunately I'm currently busy and not able to solve this issue until next week. However, if your solution works, feel free to fork project and create pull request. That might speed up things little bit :)

**Comment by fuelxc** [comment]
working on it, but not a big JS guy,  how do you run the webpack. I am getting `Couldn't find preset "react-native" relative to directory`

**Comment by juhoen** [comment]
You can generate webpack by running
`npm run webpack`. Unfornately the project currently doesn't include simply way to test webpacks so you have to do it manually. Open file with the browser and use developer tools to debug. Hope this helps!

**Comment by fuelxc** [comment]
ok, that is where I am getting the 
`
> browserify lib/webpack.js -o web/hybrid-crypto.js -t [ babelify --presets [ react-native ] ]

Error: Couldn't find preset "react-native" relative to directory "./hybrid-crypto-js" while parsing file: ./hybrid-crypto-js/lib/webpack.js
`

I am more or less muddling my way through, thanks!

**Comment by fuelxc** [comment]
yeah, i am actually at a loss.  I still get back a string so not sure where to go.  sorry

**Comment by juhoen** [comment]
No problem, I will take a look later on.
