### ISSUE TITLE
ReferenceError: Crypt is not defined

### ISSUE THREAD

**Issue by tatmush** [juhoen/hybrid-crypto-js#5]
Initializing Crypt() wont work. Console gives an error `Uncaught ReferenceError: Crypt is not defined.` I have tried initializing it like so `var crypt=new Crypt();`. I am trying to encrypt data on the client's browser. I have used this [hybrid-crypto.min.js](https://raw.githubusercontent.com/juhoen/hybrid-crypto-js/master/web/hybrid-crypto.min.jsl)
Please assist me! I'm still new to JavaScript and might be missing something very simple.
I'm stuck and want to complete the project i am working on.

**Comment by manishsingh10895** [comment]
same problem

**Comment by manishsingh10895** [comment]
For anyone else with the same problem,  use lower case crypt

var cr = new crypt();

**Comment by harishdrish123** [comment]
Getting below error:

 bytes = forge.util.encodeUtf8(String(input));
              ^
ReferenceError: bytes is not defined

**Comment by nokoh** [comment]
I'm also experiencing this same issue.

**Comment by pwFoo** [comment]
Duplicate of #15?

**Comment by juhoen** [comment]
This should be fixed in commit d79d218.
