### ISSUE TITLE
Allow for other Message Digests than SHA1 when signing 

### ISSUE THREAD

**Issue by oslc15** [juhoen/hybrid-crypto-js#6]
Hey there! I am just wondering if you have any plans to support other message digests than sha1 when signing. I am currently using SHA256 in a project and would love the possibility of freely switching between SHA1, SHA256 or w/e forge has support for! 

Thanks in advance!

**Comment by juhoen** [comment]
Hi! I'm curretly busy with an another project, buy feel free to fork project and make pull request. Good suggestion though, I'll implement it later if still necessary :)

**Comment by oslc15** [comment]
i understand! Will see what i can do =)

**Comment by juhoen** [comment]
Hybrid Crypto JS is now supporting sha1, sha256, sha384, sha512 and md5.
https://github.com/juhoen/hybrid-crypto-js/releases/tag/v0.2.1
