### ISSUE TITLE
crypto only works whilst remote debugging

### ISSUE THREAD

**Issue by oslc15** [juhoen/hybrid-crypto-js#7]
Hi again!
I have noticed that this library only works while being connected to the remote debugging. I think it has to do with crypto having a dependency towards node which is not available outside the remote debugger.

Would be happy if someone knows a workaround
Thanks!

**Comment by whizdummy** [comment]
Same problem...

**Comment by chronikum** [comment]
Actually, it is working. Try to generate keys with 1024 length, it is probably just very slow.
I think [this one](https://github.com/juhoen/hybrid-crypto-js/issues/16) is about the same problem.
