### ISSUE TITLE
bytes is not defined

### ISSUE THREAD

**Issue by harishdrish123** [juhoen/hybrid-crypto-js#8]
Getting below error:

bytes = forge.util.encodeUtf8(String(input));
^
ReferenceError: bytes is not defined

**Comment by NipunRuwanpathirana** [comment]
Same here. My dependencies are,
```
"dependencies": {
    "ajv": "^6.5.2",
    "expo": "^25.1.2",
    "hybrid-crypto-js": "^0.1.6",
    "react": "^16.4.2",
    "react-art": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-forge": "0.0.1",
    "react-native": "^0.56.0",
    "react-native-web": "^0.8.9",
    "react-scripts": "1.1.4"
  }
```

**Comment by cintolas** [comment]
The following 1 line fix will fix this

https://github.com/juhoen/hybrid-crypto-js/pull/13/commits/aa5f3d8bb2ad9e9d0c2dbdb2f0060de881784419
